apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: configmap-watcher
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  resource:
    example:
      eventTypes:
        - ADD
        - UPDATE
      group: ""
      version: "v1"
      resource: "configmaps"
      namespace: default