apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: configmap-trigger-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: configmap-dep
      eventSourceName: configmap-watcher
      eventName: example
  triggers:
    - template:
        name: trigger-python-workflow
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: python-app-workflow-
              spec:
                entrypoint: run-python-app
                templates:
                  - name: run-python-app
                    container:
                      image: myregistry/python-app:latest
                      command: ["python3"]
                      args: ["main.py", "--input", "file.txt", "--mode", "fast"]
          parameters: []