apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: python-app-workflow-
  namespace: argo
spec:
  entrypoint: run
  arguments:
    parameters:
      - name: input
        valueFrom:
          configMapKeyRef:
            name: python-app-config
            key: input
      - name: mode
        valueFrom:
          configMapKeyRef:
            name: python-app-config
            key: mode
  templates:
    - name: run
      inputs:
        parameters:
          - name: input
          - name: mode
      container:
        image: python:3.11-slim
        command: ["python3"]
        args:
          - -c
          - |
            print("Input: {{inputs.parameters.input}}")
            print("Mode: {{inputs.parameters.mode}}")