apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: python-app-workflow
  namespace: argo
spec:
  entrypoint: run-python-app
  templates:
    - name: run-python-app
      container:
        image: python:3.11-slim
        command: ["python3"]
        args: ["-c", "print('Hello from Argo! Args:', '--input=file.txt', '--mode=fast')"]